import Link from "next/link";
import styles from "./vision.module.css";

const phases=[
  {n:"PHASE 1 · 0-90 DAYS",title:"Dealer Lifecycle + Claim-to-Settlement",text:"Deliver the exact challenge with measurable departmental control gains.",items:["Onboarding / renewal + Dealer Passport","IRN/QR-first invoice intelligence + OCR fallback","Claim Truth + Scheme Packs + maker-checker","IFMS/PFMS handoff + UTR reconciliation + alerts"]},
  {n:"PHASE 2 · 3-12 MONTHS",title:"Agriculture Payment Evidence Fabric",text:"Reuse the same governed primitives across authorised Agriculture payment journeys.",items:["Common Dealer Passport and evidence packet","Cross-scheme exception taxonomy","District/state SLA and reconciliation mission control","Agriculture / Horticulture / Marketing scheme packs"]},
  {n:"PHASE 3 · FUTURE INTEROPERABILITY",title:"FarmGraph AI Intelligence Layer",text:"Connect consented and authorised evidence into planning intelligence - not into autonomous expenditure.",items:["Crop-cycle input demand forecasting","Dealer-network access deserts","Scheme utilisation vs agronomic need","Seasonal procurement and extension targeting"]},
  {n:"PHASE 4 · REUSABLE STATE ASSET",title:"Public Expenditure Evidence Engine",text:"Generalise the bounded control-plane pattern only after Agriculture proves value.",items:["Reusable evidence + rule + exception primitives","Department-owned configuration and audit","No Syntheon wallet / no public-money custody","State-owned handover and replication blueprint"]}
];

export default function VisionPage(){return <main className={styles.page}>
  <header className={styles.top}><div className={styles.gov}><b>Government of Rajasthan</b><span>Agriculture Finance Operations · Vision & Scale</span></div><Link className={styles.back} href="/dashboard">← Return to Operations</Link></header>
  <div className={styles.wrap}>
    <section className={styles.hero}><div className={styles.heroMain}><span className={styles.eyebrow}>STATEWIDE VISION · EVALUATOR VIEW</span><h1>From delayed dealer bills to a Rajasthan Agriculture Payment Evidence Fabric.</h1><p><strong>RAJ-AGRIPAY stays ruthlessly aligned to the current challenge:</strong> dealer onboarding/renewal, invoice evidence, governed scheme checks, authorised finance handoff, dealer transparency and reconciliation. The architecture is deliberately reusable so a successful 90-day pilot becomes a State capability rather than another one-off portal.</p></div><aside className={styles.heroSide}><div className={styles.decision}><span>90-DAY DECISION REQUEST</span><b>Approve a measured pilot · ₹44.8 lakh indicative ask</b></div><div className={styles.stats}><div className={styles.stat}><span>Clean validation target</span><b>&lt;4h median</b></div><div className={styles.stat}><span>Department approval target</span><b>≤T+2 days</b></div><div className={styles.stat}><span>Lineage target</span><b>100%</b></div><div className={styles.stat}><span>Eligible auto-reconcile</span><b>≥90%</b></div></div></aside></section>

    <section className={styles.section}><div className={styles.sectionHead}><div><span>01 · STATEWIDE ROADMAP</span><h2>One challenge solution. Four bounded horizons.</h2></div><p>Future layers are explicitly separated from 90-day acceptance scope.</p></div><div className={styles.roadmap}>{phases.map(p=><article className={styles.phase} key={p.n}><small>{p.n}</small><h3>{p.title}</h3><p>{p.text}</p><ul>{p.items.map(i=><li key={i}>{i}</li>)}</ul></article>)}</div></section>

    <section className={styles.section}><div className={styles.grid}><article className={`${styles.card} ${styles.span7}`}><h3>State architecture: operational evidence before expenditure</h3><div className={styles.arch}><div className={styles.archBox}><span>AUTHORITATIVE AGRICULTURE</span><b>RajKisan + dealer/licence context</b><p>Source-owned identity, licence, scheme and lifecycle references.</p></div><div className={styles.arrow}>→</div><div className={styles.archBox}><span>RAJ-AGRIPAY CONTROL PLANE</span><b>Dealer Passport + Claim Truth + Scheme Packs</b><p>Invoice evidence, deterministic rules, exception ownership, human authority and audit lineage.</p></div><div className={styles.arrow}>→</div><div className={styles.archBox}><span>AUTHORITATIVE FINANCE</span><b>Raj Sewa Dwaar → IFMS / PFMS / banks</b><p>Government rails settle. RAJ-AGRIPAY consumes acknowledgement/UTR to close reconciliation.</p></div></div></article><article className={`${styles.card} ${styles.span5}`}><h3>What becomes measurably better</h3><div className={styles.signalList}><div className={styles.signal}><i/><div><b>Dealer cash-flow visibility</b><span>Know where each claim is, why it is held and what action clears it.</span></div></div><div className={styles.signal}><i/><div><b>Officer exception ownership</b><span>Clean claims move fast; humans spend time only on explainable exceptions.</span></div></div><div className={styles.signal}><i/><div><b>Finance reconciliation</b><span>Claim → approval → acknowledgement → UTR becomes one searchable evidence chain.</span></div></div><div className={styles.signal}><i/><div><b>Scheme agility</b><span>New scheme onboarding becomes governed configuration, not another siloed application.</span></div></div></div></article></div></section>

    <section className={styles.section}><div className={styles.sectionHead}><div><span>02 · FARMGRAPH AI FUTURE</span><h2>Use payment/input evidence as a planning signal - not as an excuse for scope creep.</h2></div></div><div className={styles.grid}><article className={`${styles.card} ${styles.span8}`}><table className={styles.matrix}><thead><tr><th>Future signal</th><th>FarmGraph role</th><th>State decision enabled</th><th>Boundary</th></tr></thead><tbody><tr><td><b>Dealer claim + product + district + season</b></td><td>Input-demand feature</td><td>Anticipate crop-cycle demand pressure</td><td>Only consented/authorised event data</td></tr><tr><td><b>Dealer coverage + rejected/abandoned demand</b></td><td>Access-gap graph</td><td>Identify input-service deserts</td><td>No automated dealer scoring/penalty</td></tr><tr><td><b>Scheme utilisation + crop/soil/weather context</b></td><td>Need-vs-utilisation view</td><td>Better targeting and scheme planning</td><td>Authoritative agronomy/rules stay external</td></tr><tr><td><b>Satellite / drone / farm evidence</b></td><td>Optional future evidence node</td><td>Outcome measurement and extension targeting</td><td>Not a current evaluator integration</td></tr></tbody></table></article><article className={`${styles.card} ${styles.span4}`}><div className={styles.boundary}><b>FarmGraph safety boundary</b><p>Future digital-twin intelligence may explain, forecast and prioritise. It does not silently mutate Farmer Registry, land, scheme or payment truth and does not exercise expenditure authority.</p></div><p><b>Why it matters:</b> RAJ-AGRIPAY can become the transaction/evidence rail that FarmGraph AI later learns from, giving Rajasthan continuity from farmer need → input supply → scheme claim → payment → outcome.</p></article></div></section>

    <section className={styles.section}><div className={styles.sectionHead}><div><span>03 · 90-DAY IMPLEMENTATION</span><h2>Brownfield pilot with gates, parallel run and handover.</h2></div></div><div className={styles.timeline}><div className={styles.milestone}><span>DAY 0-10</span><b>Baseline + inventory</b><p>AS-IS, schemes, dealer master crosswalk, open obligations, interface register, baseline TAT.</p></div><div className={styles.milestone}><span>DAY 10-25</span><b>Dealer + invoice foundations</b><p>Dealer Passport, renewal, payee mapping, IRN/QR and OCR fallback.</p></div><div className={styles.milestone}><span>DAY 25-45</span><b>Claim intelligence</b><p>Scheme Packs, Claim Truth, duplicates, rates, quantities, exception workbench.</p></div><div className={styles.milestone}><span>DAY 45-60</span><b>Finance orchestration</b><p>State/CSS route, Raj eSign, e-Sanchar, acknowledgement and lineage contracts.</p></div><div className={styles.milestone}><span>DAY 60-82</span><b>Reconcile + migrate</b><p>District MIS, auto-reconcile, SUTRA/BHASHINI option, parallel replay and cutover rehearsal.</p></div><div className={styles.milestone}><span>DAY 82-90</span><b>Production + handover</b><p>Security, accessibility, restore test, SOPs, training, source/config handover and scale blueprint.</p></div></div></section>

    <section className={styles.section}><div className={styles.grid}><article className={`${styles.card} ${styles.span6}`}><h3>Why this can be delivered</h3><p>We deliberately reuse Rajasthan's existing systems rather than rebuild them. The pilot needs approved interface access, data mappings, role/security scope and hosting - not a new payment network. Structured invoice evidence reduces OCR dependence. Scheme logic is configuration-driven. SUTRA is optional and risk-tiered.</p></article><article className={`${styles.card} ${styles.span6}`}><h3>What Rajasthan owns after the pilot</h3><p>Source, OpenAPI contracts, Scheme Pack schemas, data dictionary, interface register, security controls, migration reconciliation, UAT evidence, SOP/runbooks, training, RACI, backup/DR design and statewide rollout sequence. No data monetisation, no percentage of Government payments and no lock-in to a proprietary payment rail.</p></article></div></section>
    <footer className={styles.footer}><span>RAJ-AGRIPAY · Syntheon Tech Private Limited · iStart 3B9D9E48</span><span>Future vision is explicitly truth-labelled and separated from pilot acceptance.</span></footer>
  </div>
</main>}
