"use client";

import { useMemo, useState } from "react";
import { claims as seedClaims, integrationStatus, type Claim } from "@/lib/data";

type View = "Command Centre" | "Claims" | "Dealers" | "Schemes" | "Reconciliation" | "Integrations" | "SUTRA Edge";
const fmt = (n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
const nav:{label:View;mark:string}[]=[
  {label:"Command Centre",mark:"◫"},{label:"Claims",mark:"▤"},{label:"Dealers",mark:"◎"},{label:"Schemes",mark:"⌘"},{label:"Reconciliation",mark:"↔"},{label:"Integrations",mark:"⌁"},{label:"SUTRA Edge",mark:"◈"}
];

export default function Home(){
  const [view,setView]=useState<View>("Command Centre");
  const [claims,setClaims]=useState(seedClaims);
  const [selected,setSelected]=useState<Claim|null>(seedClaims[0]);
  const [query,setQuery]=useState("");
  const [assistant,setAssistant]=useState("Ask about a claim, payment, exception or dealer.");
  const [filter,setFilter]=useState("All");
  const total=useMemo(()=>claims.reduce((a,c)=>a+c.amount,0),[claims]);
  const progressed=useMemo(()=>claims.filter(c=>c.status!=="Exception").reduce((a,c)=>a+c.amount,0),[claims]);
  const exceptions=useMemo(()=>claims.filter(c=>c.status==="Exception").reduce((a,c)=>a+c.amount,0),[claims]);
  const visible=claims.filter(c=>filter==="All"||c.status===filter);

  const approve=(id:string)=>{setClaims(p=>p.map(c=>c.id===id?{...c,status:"In finance" as const,age:"just now"}:c));setSelected(p=>p?.id===id?{...p,status:"In finance",age:"just now"}:p)};
  const ask=()=>{const q=query.toLowerCase();const hit=claims.find(c=>q.includes(c.id.toLowerCase())||q.includes(c.dealer.toLowerCase().split(" ")[0]));if(hit)setAssistant(`${hit.id} is ${hit.status.toLowerCase()}. ${hit.exception?hit.exception:`All ${hit.totalChecks} automated checks are complete.`} Route: ${hit.route}.`);else if(q.includes("payment")||q.includes("पैसे")||q.includes("भुगतान"))setAssistant("2 claims are in exception. The largest blocked value is ₹3.11L due to a duplicate IRN. External payment SLA is never fabricated; status appears only after source acknowledgement.");else setAssistant("I can explain claim status, rule failures, dealer validity and finance routing from the evidence graph. Try AGR-26-10479.")};

  return <main className="shell">
    <aside className="sidebar">
      <div className="brand"><div className="crest">R</div><div><strong>RAJ-AGRIPAY</strong><span>Agriculture Dealer Control Plane</span></div></div>
      <div className="env"><span className="pulse"/> Evaluation Sandbox</div>
      <nav>{nav.map(n=><button key={n.label} className={view===n.label?"active":""} onClick={()=>setView(n.label)}><b>{n.mark}</b>{n.label}</button>)}</nav>
      <div className="sideCard"><small>CORE PRINCIPLE</small><strong>Orchestrate, don&apos;t duplicate.</strong><p>RajKisan and IFMS remain systems of record. RAJ-AGRIPAY adds Agriculture-specific claim intelligence and reconciliation.</p></div>
      <div className="sideFoot"><span>●</span> API status: healthy</div>
    </aside>

    <section className="workspace">
      <header className="topbar"><div><span className="eyebrow">Government of Rajasthan · Department of Agriculture</span><h1>{view}</h1></div><div className="headerActions"><button className="ghost">हिंदी</button><button className="profile">AK<span>Scheme Officer</span></button></div></header>

      {view==="Command Centre"&&<>
        <section className="hero"><div><span className="heroLabel">CLAIM → SETTLEMENT OPERATING LAYER</span><h2>Every dealer claim becomes an <em>evidence-backed payment packet.</em></h2><p>Unify dealer lifecycle, scheme rules, invoice validation, finance routing and reconciliation—without replacing RajKisan, IFMS 3.0, PFMS or Treasury.</p></div><div className="heroRail">{["Dealer","Claim","Truth Graph","Approval","IFMS/PFMS","UTR"].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b></div>)}</div></section>
        <section className="metrics"><Metric label="Claims in view" value={fmt(total)} sub="5 evaluation claims"/><Metric label="Clean / progressed" value={fmt(progressed)} sub="deterministic checks passed" positive/><Metric label="Exception value" value={fmt(exceptions)} sub="2 claims need action" warning/><Metric label="Median clean validation" value="2h 14m" sub="pilot dashboard simulation" positive/></section>
        <section className="grid2"><div className="panel"><PanelTitle kicker="LIVE OPERATIONS" title="Claim queue" action="Open claims" onAction={()=>setView("Claims")}/><div className="claimList">{claims.slice(0,4).map(c=><button key={c.id} className="claimRow" onClick={()=>{setSelected(c);setView("Claims")}}><div><strong>{c.id}</strong><span>{c.dealer}</span></div><div><b>{fmt(c.amount)}</b><span>{c.scheme}</span></div><Status value={c.status}/></button>)}</div></div>
          <div className="panel saarthi"><PanelTitle kicker="BHASHINI-READY" title="Dealer Saarthi"/><div className="assistantReply">{assistant}</div><div className="ask"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} placeholder="Ask: मेरा भुगतान कहाँ अटका है?"/><button onClick={ask}>Ask</button></div><div className="quick"><button onClick={()=>{setQuery("AGR-26-10479");setAssistant("AGR-26-10479 is in exception. Bank account changed 3 days before payment; re-verification is required before finance handoff.")}}>Explain exception</button><button onClick={()=>{setQuery("payment");setAssistant("2 claims are in exception. The largest blocked value is ₹3.11L due to a duplicate IRN.")}}>Payment blockers</button></div></div>
        </section>
        <section className="grid3"><div className="panel span2"><PanelTitle kicker="CLAIM TRUTH GRAPH" title="Evidence before expenditure"/><div className="truthGraph">{[["Dealer","Licence valid · GST matched · bank verified"],["Invoice","IRN/QR first · OCR fallback · duplicate guard"],["Scheme","Rate · quantity · period · sanction · rule version"],["Delivery","Order/beneficiary/evidence references"],["Finance","Fund route · approval · acknowledgement · UTR"]].map(([a,b],i)=><div key={a}><span>{i+1}</span><strong>{a}</strong><p>{b}</p></div>)}</div></div><div className="panel"><PanelTitle kicker="SLA WATCH" title="What needs attention"/><Alert kind="high" n="1" title="Duplicate IRN blocked" sub="₹3.11L protected"/><Alert kind="med" n="1" title="Bank change hold" sub="re-verification required"/><Alert kind="good" n="3" title="Claims clean" sub="ready / finance / paid"/></div></section>
      </>}

      {view==="Claims"&&<section className="claimsView"><div className="panel claimTablePanel"><PanelTitle kicker="UNIFIED CLAIM LEDGER" title="Claims & exceptions"/><div className="filters">{["All","Ready for approval","In finance","Exception","Paid"].map(f=><button key={f} onClick={()=>setFilter(f)} className={filter===f?"selected":""}>{f}</button>)}</div><div className="tableWrap"><table><thead><tr><th>Claim</th><th>Dealer</th><th>Scheme</th><th>Amount</th><th>Evidence</th><th>Status</th></tr></thead><tbody>{visible.map(c=><tr key={c.id} onClick={()=>setSelected(c)} className={selected?.id===c.id?"picked":""}><td><strong>{c.id}</strong><small>{c.invoice}</small></td><td>{c.dealer}<small>{c.district} · {c.gstin}</small></td><td>{c.scheme}<small>{c.route}</small></td><td><strong>{fmt(c.amount)}</strong><small>age {c.age}</small></td><td><b>{c.checks}/{c.totalChecks}</b><small>{c.risk} risk</small></td><td><Status value={c.status}/></td></tr>)}</tbody></table></div></div>
        {selected&&<div className="panel inspector"><PanelTitle kicker="EVIDENCE PACKET" title={selected.id}/><div className="inspectorAmount">{fmt(selected.amount)}<span>{selected.dealer}</span></div><div className="checkGrid">{["Dealer licence valid","GSTIN matches dealer","Invoice uniqueness","Scheme item eligible","Rate within ceiling","Quantity within sanction","Claim period valid","Bank profile verified","Delivery evidence present","Deduction rules applied","Fund route resolved","Audit packet complete"].map((x,i)=><div className={i<selected.checks?"pass":"fail"} key={x}><span>{i<selected.checks?"✓":"!"}</span>{x}</div>)}</div>{selected.exception&&<div className="exceptionBox"><b>Exception reason</b><p>{selected.exception}</p></div>}<div className="routeBox"><small>FINANCE ROUTE</small><b>{selected.route}</b><span>External settlement status is displayed only after authoritative acknowledgement.</span></div>{selected.status==="Ready for approval"&&<button className="primary" onClick={()=>approve(selected.id)}>Approve evidence packet → Finance</button>}</div>}
      </section>}

      {view==="Dealers"&&<section className="grid2"><div className="panel spanFull"><PanelTitle kicker="UNIFIED DEALER PASSPORT" title="One agriculture dealer identity across schemes"/><div className="dealerPassport"><div className="dealerHead"><div className="avatar">SB</div><div><h3>Shree Balaji Agro Centre</h3><p>Dealer ID · RAD-JAI-002814</p></div><span className="verified">✓ VERIFIED</span></div><div className="passportGrid">{[["RajKisan licence","Fertilizer retail · Valid to 28 Sep 2028"],["IFMS vendor","Mapped · payee profile active"],["GSTIN","08AACFS4821K1ZQ · matched"],["Bank profile","Verified · last change 214 days ago"],["Jurisdiction","Jaipur · Zone 3"],["Schemes","3 active · 1 renewal upcoming"]].map(([a,b])=><div key={a}><small>{a}</small><strong>{b}</strong></div>)}</div></div></div><div className="panel"><PanelTitle kicker="LIFECYCLE" title="Renewals & compliance"/><div className="timeline"><p><b>63 days</b><span>Seed licence renewal window opens</span></p><p><b>214 days</b><span>Since last bank profile change</span></p><p><b>0</b><span>Critical compliance holds</span></p></div></div><div className="panel"><PanelTitle kicker="PAYMENT IDENTITY LOCK" title="Sensitive changes need dual control"/><p className="bodyText">Bank changes are versioned, re-verified and maker-checker approved before affecting future payment packets. Historical claims retain the bank-profile version used at approval.</p><div className="miniFlow"><span>Dealer request</span><i>→</i><span>Re-KYC</span><i>→</i><span>Checker</span><i>→</i><span>New version</span></div></div></section>}

      {view==="Schemes"&&<section className="grid2"><div className="panel spanFull"><PanelTitle kicker="LOW-CODE RULE STUDIO" title="Onboard schemes without rebuilding software"/><div className="ruleMeta"><label>Scheme name<input value="Certified Seed Support" readOnly/></label><label>Effective version<input value="v3.4 · 01 Sep 2026" readOnly/></label><label>Finance route<input value="IFMS 3.0 · State Scheme" readOnly/></label></div><div className="rules">{[["Dealer class","Seed / multi-input dealer"],["Licence","Valid seed licence required"],["Rate ceiling","₹30,000 per eligible unit"],["Invoice evidence","IRN/QR preferred; OCR fallback"],["Approval","Maker → Checker → Approver"],["Reconciliation","Claim + bill + UTR required"]].map(([a,b])=><div key={a}><strong>{a}</strong><span>{b}</span><button>Edit</button></div>)}</div><div className="versionNote">Every rule change is effective-dated, versioned and approval-traced. Old claims continue to evaluate against the rule version valid on their transaction date.</div></div></section>}

      {view==="Reconciliation"&&<section className="grid2"><div className="panel spanFull"><PanelTitle kicker="CLAIM → UTR LINEAGE" title="Make year-end closure an exception exercise"/><div className="reconFlow">{["Claim","Approval","Sanction","IFMS packet","Payment acknowledgement","UTR","Reconciled"].map((x,i)=><div className="done" key={x}><span>{i+1}</span><b>{x}</b></div>)}</div></div><div className="panel"><PanelTitle kicker="AUTO-RECONCILED" title="AGR-26-10477"/><Ledger rows={[["Claimed","₹1,28,500"],["Approved","₹1,28,500"],["Paid","₹1,28,500"],["UTR","RBIGOR26X98172"],["Status","✓ Reconciled"]]} final="green"/></div><div className="panel"><PanelTitle kicker="EXCEPTION" title="Bank rejection simulation"/><Ledger rows={[["Approved","₹2,38,800"],["Paid","₹0"],["Reason","Account re-verification"],["Owner","Dealer + Checker"],["Status","⚠ Action required"]]} final="amber"/></div></section>}

      {view==="Integrations"&&<section className="panel integrationPanel"><PanelTitle kicker="NO FAKE APIS" title="Integration readiness matrix"/><p className="bodyText max">The prototype distinguishes authoritative systems from sandbox and contract-ready adapters. Government credentials, network access and approvals are explicit deployment dependencies—not silently simulated production integrations.</p><div className="integrationGrid">{integrationStatus.map(i=><div key={i.name}><div><strong>{i.name}</strong><p>{i.note}</p></div><span className={`tag ${i.status.toLowerCase().replaceAll("-","")}`}>{i.status}</span></div>)}</div><div className="architecture"><span>RajKisan</span><i>→</i><b>RAJ-AGRIPAY</b><i>→</i><span>Raj Sewa Dwaar</span><i>→</i><span>IFMS / PFMS</span><i>→</i><span>RBI / Bank</span></div></section>}

      {view==="SUTRA Edge"&&<section className="grid2"><div className="panel sutraHero"><span className="heroLabel">OPTIONAL ASSISTED CHANNEL</span><h2>SUTRA Dealer Edge</h2><p>For district offices, camps and low-connectivity contexts: scan evidence, guide the dealer in Hindi, capture human confirmation, queue the packet securely and sync through approved infrastructure when connectivity returns.</p><div className="device"><div className="screen"><b>RAJ-AGRIPAY</b><span>Dealer assisted mode</span><div className="voice">◉ “मेरा भुगतान कहाँ अटका है?”</div><div className="answer">2 bills need action. One requires bank re-verification.</div></div><div className="grill">SUTRA-ID EDGE</div></div></div><div className="panel"><PanelTitle kicker="WHY IT MATTERS" title="Edge where edge is useful"/><div className="edgeList">{[["Voice","BHASHINI-ready Hindi ASR/TTS adapter"],["Camera","Invoice / licence / supporting-evidence capture"],["Offline","Queue non-financial capture until approved sync"],["Human confirmation","No autonomous Government approval"],["Receipt","Evidence-linked local transaction receipt"]].map(([a,b])=><div key={a}><strong>{a}</strong><span>{b}</span></div>)}</div><div className="note">SUTRA is an optional access channel—not a hardware dependency for statewide rollout.</div></div></section>}

      <footer><span>RAJ-AGRIPAY v0.1 · Evaluation Prototype</span><span>LIVE / SANDBOX / CONTRACT-READY clearly separated</span></footer>
    </section>
  </main>
}

function Metric({label,value,sub,positive,warning}:{label:string;value:string;sub:string;positive?:boolean;warning?:boolean}){return <div className="metric"><span>{label}</span><strong>{value}</strong><small className={positive?"pos":warning?"warn":""}>{positive?"↑ ":warning?"⚠ ":""}{sub}</small></div>}
function Status({value}:{value:string}){return <span className={`status ${value.toLowerCase().replaceAll(" ","")}`}>{value}</span>}
function PanelTitle({kicker,title,action,onAction}:{kicker:string;title:string;action?:string;onAction?:()=>void}){return <div className="panelTitle"><div><small>{kicker}</small><h3>{title}</h3></div>{action&&<button onClick={onAction}>{action} →</button>}</div>}
function Alert({kind,n,title,sub}:{kind:string;n:string;title:string;sub:string}){return <div className={`alert ${kind}`}><b>{n}</b><span>{title}<p>{sub}</p></span></div>}
function Ledger({rows,final}:{rows:string[][];final:string}){return <div className="ledger">{rows.map(([a,b],i)=><p key={a} className={i===rows.length-1?final:""}><span>{a}</span><b>{b}</b></p>)}</div>}
